name: Basic Crud in Django Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Set up Python 3.13
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'
        cache: 'pip' # Speeds up subsequent runs by caching dependencies

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

#    - name: Set up environment variables
#      run: cp contrib/env-sample .env

    - name: Run flake8
      run: flake8 .

    - name: Run Pytest
      run: |
        pytest webdev
